### PR TITLE
(fix): ignore empty GraphQL documents

### LINKED ISSUE #6: Nuxt crashes on code generation due to empty GraphQL Document(s)
Nuxt crashes when:
- an **empty GraphQL Document** is added while the dev server is running.
- the only GraphQL Document(s) present are **empty** when `yarn dev` or `yarn build` is ran.

### PR DESCRIPTION
**Pull request by Diizzayy**
Resolves #6

This PR simply adds a check to see if scanned GraphQL documents are empty.

### CODE REVIEW

File: src/module.ts [hunk 1]
```diff
@@ -179,8 +179,6 @@ export default defineNuxtModule<ModuleOptions>({
         getContents: () => ctx.generateDeclarations(),
       })
 
-      // Known bug: isn't triggered on `generateApp`. Hence, your dev server
```
Comment (Diizzayy) [inline src/module.ts:182]: This bug was addressed by nuxt/framework#3480
